on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v5
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: tuxbubbles.flatpak
        manifest-path: build-aux/org.elliotnash.TuxBubbles.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
